In [ ]:
# Continuar com a lógica com as datas numéricas.

In [3]:
import pandas as pd
import re

In [4]:
series = pd.Series(dtype='object')
f = open('dates.txt')
i = 0
for line in f:
    series.loc[i] = line
    i+=1
series.head()

0         03/25/93 Total time of visit (in minutes):\n
1                       6/18/85 Primary Care Doctor:\n
2    sshe plans to move as of 7/8/71 In-Home Servic...
3                7 on 9/27/75 Audit C Score Current:\n
4    2/6/96 sleep studyPain Treatment Pain Level (N...
dtype: object

In [5]:
sample = series.iloc[[i for i in range(0,len(series),20)]]

In [214]:
# Numeric.
numeric='((\d{,2}[/-])?(\d{,2}[/-])?(\d{2,4}))'
sample.str.extractall(numeric)

                  0    1    2     3
    match
0   0      03/25/93  03/  25/    93
20  0       7/21/98   7/  21/    98
40  0       7-29-75   7-  29-    75
    1          9080  NaN  NaN  9080
60  0       7/24/95   7/  24/    95
    1           -10    -  NaN    10
80  0         10-15  10-  NaN    15
    1       6/29/81   6/  29/    81
100 0       8/16/92   8/  16/    92
    1           -10    -  NaN    10
120 0      12/22/98  12/  22/    98
    1          9080  NaN  NaN  9080
140 0            14  NaN  NaN    14
    1          1995  NaN  NaN  1995
160 0            21  NaN  NaN    21
    1          2007  NaN  NaN  2007
180 0            09  NaN  NaN    09
    1          1988  NaN  NaN  1988
200 0            26  NaN  NaN    26
    1          1978  NaN  NaN  1978
220 0            25  NaN  NaN    25
    1          2012  NaN  NaN  2012
240 0            37  NaN  NaN    37
    1          2011  NaN  NaN  2011
260 0          2000  NaN  NaN  2000
280 0          1985  NaN  NaN  1985
300 0          1994  NaN  NaN  1994
320 0            50  NaN  NaN    50
    1            16  NaN  NaN    16
    2          2012  NaN  NaN  2012
340 0          1980  NaN  NaN  1980
360 0       12/2008  12/  NaN  2008
380 0        7/1973   7/  NaN  1973
400 0       11/2008  11/  NaN  2008
420 0        3/2000   3/  NaN  2000
    1           911  NaN  NaN   911
440 0        6/1989   6/  NaN  1989
460 0          2012  NaN  NaN  2012
480 0          2013  NaN  NaN  2013

In [228]:
# Alpha.
months_list=['Jan', 'Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec']
alpha='((\d{1,2})? ?(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)[a-z.]* ?(\d{1,2})?[,]? (\d{4}))'

sample.str.extractall(alpha)

                        0    1    2    3     4
    match
140 0         14 Feb 1995   14  Feb  NaN  1995
160 0         21 Oct 2007   21  Oct  NaN  2007
180 0         09 Dec 1988   09  Dec  NaN  1988
200 0       July 26, 1978  NaN  Jul   26  1978
220 0       June 25, 2012  NaN  Jun   25  2012
240 0           May, 2011  NaN  May  NaN  2011
260 0       February 2000  NaN  Feb  NaN  2000
280 0           July 1985  NaN  Jul  NaN  1985
300 0        January 1994  NaN  Jan  NaN  1994
320 0       November 2012  NaN  Nov  NaN  2012
340 0            May 1980  NaN  May  NaN  1980

In [342]:
# Numeric.
numeric='((\d{,2}[/-])?(\d{,2}[/-])?(\d{2,4}))'
sample.str.extractall(numeric)

                  0    1    2     3
    match
0   0      03/25/93  03/  25/    93
20  0       7/21/98   7/  21/    98
40  0       7-29-75   7-  29-    75
    1          9080  NaN  NaN  9080
60  0       7/24/95   7/  24/    95
    1           -10    -  NaN    10
80  0         10-15  10-  NaN    15
    1       6/29/81   6/  29/    81
100 0       8/16/92   8/  16/    92
    1           -10    -  NaN    10
120 0      12/22/98  12/  22/    98
    1          9080  NaN  NaN  9080
140 0            14  NaN  NaN    14
    1          1995  NaN  NaN  1995
160 0            21  NaN  NaN    21
    1          2007  NaN  NaN  2007
180 0            09  NaN  NaN    09
    1          1988  NaN  NaN  1988
200 0            26  NaN  NaN    26
    1          1978  NaN  NaN  1978
220 0            25  NaN  NaN    25
    1          2012  NaN  NaN  2012
240 0            37  NaN  NaN    37
    1          2011  NaN  NaN  2011
260 0          2000  NaN  NaN  2000
280 0          1985  NaN  NaN  1985
300 0          1994  NaN  NaN  1994
320 0            50  NaN  NaN    50
    1            16  NaN  NaN    16
    2          2012  NaN  NaN  2012
340 0          1980  NaN  NaN  1980
360 0       12/2008  12/  NaN  2008
380 0        7/1973   7/  NaN  1973
400 0       11/2008  11/  NaN  2008
420 0        3/2000   3/  NaN  2000
    1           911  NaN  NaN   911
440 0        6/1989   6/  NaN  1989
460 0          2012  NaN  NaN  2012
480 0          2013  NaN  NaN  2013

In [7]:
sample = series.iloc[[i for i in range(0,len(series),20)]]
sample1= series.loc[[i for i in range(0,len(series), 15)]]

In [37]:
a = '(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)?(January|February|March|April|May|June|July|August|September|October|November|December)?'
re.findall(a, 'PET Scan (DPSH 5/04/74): 1) Marked hypometabolism involving the bilateral caudate nuclei. This is a non-specific finding, although this raises the question of a multisystem atrophy, specifically MSA-P (striatonigral degeneration), 2) Cortical hypometabolism involving the right inferior frontal gyrus. This is a non-specific finding of uncertain significance, and is not definitively related to a neurodegenerative process, although pathology in this region is not excluded')
    #print(re.findall(a))

[('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('Mar', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', ''),
 ('', '')]

In [43]:
a = 'Me Myself'
re.sub('(Me|Myself)', '5', a)

'5 5'

In [165]:
# Uma das datas numéricas está sendo considerada como data de string.
# O seu texto tem a palavra 'Marked', que cai como uma padrão cabível em 'month_pattern'...
import re
def not_year_two(l):    
    for i in range(len(l)):
        whole, day, month, year = l[i]
        if day == '' and month =='' and len(year)==2:
            continue
        else:
            return l[i]
        
def find_date(series):
    indices = []
    new_dates = []
    months_list=['Jan', 'Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec']
    month_pattern='(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)[a-z.]*'
    prohibited_terms = '(Marked|Marital|Declined)'
    # A dictionary with the month abbreviation with its respective ordinal number (não remover, por ora).
    month_dict={months_list[i]:i+1 for i in range(len(months_list))}
    for date in series:
        #teste
        index = series[series == date].index[0]
        #print(index)
        final_date=None
        date = re.sub(prohibited_terms,'', date)
        # If the date have a word representing the month, follow this logic.
        if re.search(month_pattern, date):
            alpha='((\d{1,2})? ?(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)[a-z.]* ?(\d{1,2})?[,]? (\d{4}))'
            # Stripping possible undesirable spaces.
            date_extracted = re.findall(alpha, date)[0][0].strip()
            date_extracted = date_extracted.replace('Janaury','January').replace('Decemeber','December').replace('2June', '2 June')
            #print(date_extracted)
            # If date has no day number, insert a 1.
            #print(date_extracted)
            if len(date_extracted.split()) == 2:
                date_extracted = '1 '+date_extracted.strip()
            final_date = date_extracted.replace(',','').replace('.','')
        # Else, the date must be numeric!
        else:
            #print(date)
            numeric='((\d{,2}[/-])?(\d{,2}[/-])?(\d{2,4}))'
            # Extracting the potential dates
            potential_dates = re.findall(numeric, date)
            date_extracted = not_year_two(potential_dates)[0].replace('/','-')
            # Splitting the date on the dash.
            date_splitted = date_extracted.split('-')
            year = int(date_splitted[-1])
            # The regex might catch some random numbers that are not a date in any way.
            if len(date_splitted) == 1 and len(str(year)) <4:
                continue
            elif len(date_splitted) == 1 and len(str(year)) ==4:
                date_splitted.insert(0,str(1))
                date_splitted.insert(0,str(1))
                final_date='-'.join(date_splitted)
                #print(final_date)
            # If the given date has only the month and year numbers, add '1' as day
            elif len(date_splitted) == 2:
                date_splitted.insert(0,str(1))
                final_date = '-'.join(date_splitted)
            else:
                final_date=date_extracted
                
        #print(date_extracted,pd.to_datetime(final_date).date())
        # teste
        indices.append(index)
        new_dates.append(pd.to_datetime(final_date).date())
    extra_dates = ['8/9/97','11/14/83', '4/2013', '2007']
    for dt in extra_dates:
        new_dates.append(pd.to_datetime(dt).date())
        
    values = pd.Series(new_dates)#.sort_values().index
    return pd.Series(values).sort_values()
                
find_date(series)

0      1993-03-25
1      1985-06-18
2      2071-07-08
3      1975-09-27
4      1996-02-06
          ...
495    1980-01-01
496    1997-08-09
497    1983-11-14
498    2013-04-01
499    2007-01-01
Length: 500, dtype: object

In [160]:
new_dates = []
new_dates.append([1,2,3])
new_dates

[[1, 2, 3]]

In [155]:
new_dates

[datetime.date(1997, 8, 9),
 datetime.date(1983, 11, 14),
 datetime.date(2013, 4, 1),
 datetime.date(2007, 1, 1)]

In [148]:
x = find_date(series)

In [129]:
for i in range(500):
    if i not in x:
        print(i)

87
99
431
490

In [169]:
df

            03/25/93 Total time of visit (in minutes):
0                         6/18/85 Primary Care Doctor:
1    sshe plans to move as of 7/8/71 In-Home Servic...
2                  7 on 9/27/75 Audit C Score Current:
3    2/6/96 sleep studyPain Treatment Pain Level (N...
4                      .Per 7/06/79 Movement D/O note:
..                                                 ...
454  1979 Family Psych History: Family History of S...
455  therapist and friend died in ~2006 Parental/Ca...
456                         2008 partial thyroidectomy
457  sPt describes a history of sexual abuse as a c...
458  . In 1980, patient was living in Naples and de...

[459 rows x 1 columns]

In [186]:
# FUNÇÃO NO COURSERA (LIDAR COM A DATA '011/14/83')
df = pd.Series(pd.read_table('dates.txt').iloc[:,0].values)
import re
def not_year_two(l):    
    for i in range(len(l)):
        whole, day, month, year = l[i]
        year = day.replace('011', '11')
        if day == '' and month =='' and (len(year)==2 or len(year)==3):
            continue
        else:
            print(l[i], l)
            return l[i]
        #-8-2000 --> -8-2000
def date_sorter():
    new_dates = []
    months_list=['Jan', 'Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec']
    month_pattern='(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)[a-z.]*'
    prohibited_terms = '(Marked|Marital|Declined)'
    # A dictionary with the month abbreviation with its respective ordinal number (não remover, por ora).
    month_dict={months_list[i]:i+1 for i in range(len(months_list))}
    for date in df:
        final_date=None
        date = re.sub(prohibited_terms,'', date)
        # If the date have a word representing the month, follow this logic.
        if re.search(month_pattern, date):
            alpha='((\d{1,2})? ?(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)[a-z.]* ?(\d{1,2})?[,]? (\d{4}))'
            # Stripping possible undesirable spaces.
            date_extracted = re.findall(alpha, date)[0][0].strip()
            date_extracted = date_extracted.replace('Janaury','January').replace('Decemeber','December').replace('2June', '2 June')
            #print(date_extracted)
            # If date has no day number, insert a 1.
            #print(date_extracted)
            if len(date_extracted.split()) == 2:
                date_extracted = '1 '+date_extracted.strip()
            final_date = date_extracted.replace(',','').replace('.','')
        # Else, the date must be numeric!
        else:
            numeric='((\d{,2}[/-])?(\d{,2}[/-])?(\d{2,4}))'
            # Extracting the potential dates
            potential_dates = re.findall(numeric, date)
            date_extracted = not_year_two(potential_dates)[0].replace('/','-').replace('-8-2000', '01-08-2000')
            # Dealing with the 1971 dates, preveting them from becoming 2071.
            date_extracted = re.sub('71', '1971', date_extracted)
            # Splitting the date on the dash.
            date_splitted = date_extracted.split('-')
            year = int(date_splitted[-1])
            # The regex might catch some random numbers that are not a date in any way.
            if len(date_splitted) == 1 and len(str(year)) <4:
                continue
            elif len(date_splitted) == 1 and len(str(year)) ==4:
                date_splitted.insert(0,str(1))
                date_splitted.insert(0,str(1))
                final_date='-'.join(date_splitted)
            # If the given date has only the month and year numbers, add '1' as day
            elif len(date_splitted) == 2:
                date_splitted.insert(0,str(1))
                final_date = '-'.join(date_splitted)
            else:
                final_date=date_extracted
        print(date_splitted,'-->',date_extracted, '-->',final_date, end='\n\n')        
        new_dates.append(pd.to_datetime(final_date).date())
    extra_dates = ['8/9/97','11/14/83', '4/2013', '2007']
    indices = [87, 99, 431, 490]
    for i, dt in zip(indices, extra_dates):
        new_dates.insert(i,pd.to_datetime(dt).date())
        
    values = pd.Series(new_dates).sort_values()#.index
    return pd.Series(values)#.loc[28]
    
    #return df# Your answer here
date_sorter()

('6/18/85', '6/', '18/', '85') [('6/18/85', '6/', '18/', '85')]
['6', '18', '85'] --> 6-18-85 --> 6-18-85

('7/8/71', '7/', '8/', '71') [('7/8/71', '7/', '8/', '71')]
['7', '8', '1971'] --> 7-8-1971 --> 7-8-1971

('9/27/75', '9/', '27/', '75') [('9/27/75', '9/', '27/', '75')]
['9', '27', '75'] --> 9-27-75 --> 9-27-75

('2/6/96', '2/', '6/', '96') [('2/6/96', '2/', '6/', '96')]
['2', '6', '96'] --> 2-6-96 --> 2-6-96

('7/06/79', '7/', '06/', '79') [('7/06/79', '7/', '06/', '79')]
['7', '06', '79'] --> 7-06-79 --> 7-06-79

('5/18/78', '5/', '18/', '78') [('5/18/78', '5/', '18/', '78')]
['5', '18', '78'] --> 5-18-78 --> 5-18-78

('10/24/89', '10/', '24/', '89') [('10/24/89', '10/', '24/', '89'), ('9080', '', '', '9080')]
['10', '24', '89'] --> 10-24-89 --> 10-24-89

('3/7/86', '3/', '7/', '86') [('3/7/86', '3/', '7/', '86'), ('-10', '-', '', '10')]
['3', '7', '86'] --> 3-7-86 --> 3-7-86

('4/10/71', '4/', '10/', '71') [('4/10/71', '4/', '10/', '71')]
['4', '10', '1971'] --> 4-10-1971 --> 4-10-1971

('5/11/85', '5/', '11/', '85') [('5/11/85', '5/', '11/', '85'), ('96', '', '', '96'), ('-26', '-', '', '26'), ('-16/22', '-', '16/', '22'), ('12', '', '', '12')]
['5', '11', '85'] --> 5-11-85 --> 5-11-85

('4/09/75', '4/', '09/', '75') [('4/09/75', '4/', '09/', '75'), ('-10', '-', '', '10')]
['4', '09', '75'] --> 4-09-75 --> 4-09-75

('8/01/98', '8/', '01/', '98') [('8/01/98', '8/', '01/', '98')]
['8', '01', '98'] --> 8-01-98 --> 8-01-98

('1/26/72', '1/', '26/', '72') [('1/26/72', '1/', '26/', '72')]
['1', '26', '72'] --> 1-26-72 --> 1-26-72

('5/24/1990', '5/', '24/', '1990') [('5/24/1990', '5/', '24/', '1990'), ('9079', '', '', '9079')]
['5', '24', '1990'] --> 5-24-1990 --> 5-24-1990

('1/25/2011', '1/', '25/', '2011') [('1/25/2011', '1/', '25/', '2011'), ('9079', '', '', '9079')]
['1', '25', '2011'] --> 1-25-2011 --> 1-25-2011

('4/12/82', '4/', '12/', '82') [('4/12/82', '4/', '12/', '82')]
['4', '12', '82'] --> 4-12-82 --> 4-12-82

('10/13/1976', '10/', '13/', '1976') [('10/13/1976', '10/', '13/', '1976')]
['10', '13', '1976'] --> 10-13-1976 --> 10-13-1976

('4/24/98', '4/', '24/', '98') [('4/24/98', '4/', '24/', '98')]
['4', '24', '98'] --> 4-24-98 --> 4-24-98

('59', '', '', '59') [('59', '', '', '59'), ('5/21/77', '5/', '21/', '77')]
('7/21/98', '7/', '21/', '98') [('7/21/98', '7/', '21/', '98')]
['7', '21', '98'] --> 7-21-98 --> 7-21-98

('10/21/79', '10/', '21/', '79') [('10/21/79', '10/', '21/', '79'), ('-10', '-', '', '10')]
['10', '21', '79'] --> 10-21-79 --> 10-21-79

('3/03/90', '3/', '03/', '90') [('3/03/90', '3/', '03/', '90'), ('9079', '', '', '9079')]
['3', '03', '90'] --> 3-03-90 --> 3-03-90

('2/11/76', '2/', '11/', '76') [('2/11/76', '2/', '11/', '76'), ('9079', '', '', '9079')]
['2', '11', '76'] --> 2-11-76 --> 2-11-76

('07/25/1984', '07/', '25/', '1984') [('07/25/1984', '07/', '25/', '1984'), ('9079', '', '', '9079')]
['07', '25', '1984'] --> 07-25-1984 --> 07-25-1984

('4-13-82', '4-', '13-', '82') [('4-13-82', '4-', '13-', '82')]
['4', '13', '82'] --> 4-13-82 --> 4-13-82

('9/22/89', '9/', '22/', '89') [('9/22/89', '9/', '22/', '89'), ('9079', '', '', '9079')]
['9', '22', '89'] --> 9-22-89 --> 9-22-89

('9/02/76', '9/', '02/', '76') [('9/02/76', '9/', '02/', '76'), ('9079', '', '', '9079')]
['9', '02', '76'] --> 9-02-76 --> 9-02-76

('9/12/71', '9/', '12/', '71') [('9/12/71', '9/', '12/', '71')]
['9', '12', '1971'] --> 9-12-1971 --> 9-12-1971

('10/24/86', '10/', '24/', '86') [('10/24/86', '10/', '24/', '86')]
['10', '24', '86'] --> 10-24-86 --> 10-24-86

('03/31/1985', '03/', '31/', '1985') [('03/31/1985', '03/', '31/', '1985')]
['03', '31', '1985'] --> 03-31-1985 --> 03-31-1985

('7/20/72', '7/', '20/', '72') [('7/20/72', '7/', '20/', '72'), ('9079', '', '', '9079')]
['7', '20', '72'] --> 7-20-72 --> 7-20-72

('4/12/87', '4/', '12/', '87') [('4/12/87', '4/', '12/', '87')]
['4', '12', '87'] --> 4-12-87 --> 4-12-87

('06/20/91', '06/', '20/', '91') [('06/20/91', '06/', '20/', '91')]
['06', '20', '91'] --> 06-20-91 --> 06-20-91

('5/12/2012', '5/', '12/', '2012') [('5/12/2012', '5/', '12/', '2012')]
['5', '12', '2012'] --> 5-12-2012 --> 5-12-2012

('3/15/83', '3/', '15/', '83') [('3/15/83', '3/', '15/', '83'), ('-10', '-', '', '10')]
['3', '15', '83'] --> 3-15-83 --> 3-15-83

('2/14/73', '2/', '14/', '73') [('2/14/73', '2/', '14/', '73'), ('9080', '', '', '9080')]
['2', '14', '73'] --> 2-14-73 --> 2-14-73

('5/24/88', '5/', '24/', '88') [('5/24/88', '5/', '24/', '88'), ('9079', '', '', '9079')]
['5', '24', '88'] --> 5-24-88 --> 5-24-88

('7/27/1986', '7/', '27/', '1986') [('7/27/1986', '7/', '27/', '1986')]
['7', '27', '1986'] --> 7-27-1986 --> 7-27-1986

('1-14-81', '1-', '14-', '81') [('1-14-81', '1-', '14-', '81')]
['1', '14', '81'] --> 1-14-81 --> 1-14-81

('7-29-75', '7-', '29-', '75') [('7-29-75', '7-', '29-', '75'), ('9080', '', '', '9080')]
['7', '29', '75'] --> 7-29-75 --> 7-29-75

('6/24/87', '6/', '24/', '87') [('6/24/87', '6/', '24/', '87'), ('18', '', '', '18')]
['6', '24', '87'] --> 6-24-87 --> 6-24-87

('8/14/94', '8/', '14/', '94') [('8/14/94', '8/', '14/', '94')]
['8', '14', '94'] --> 8-14-94 --> 8-14-94

('4/13/2002', '4/', '13/', '2002') [('4/13/2002', '4/', '13/', '2002')]
['4', '13', '2002'] --> 4-13-2002 --> 4-13-2002

('8/16/82', '8/', '16/', '82') [('8/16/82', '8/', '16/', '82'), ('9079', '', '', '9079')]
['8', '16', '82'] --> 8-16-82 --> 8-16-82

('2/15/1998', '2/', '15/', '1998') [('2/15/1998', '2/', '15/', '1998')]
['2', '15', '1998'] --> 2-15-1998 --> 2-15-1998

('7/15/91', '7/', '15/', '91') [('7/15/91', '7/', '15/', '91'), ('9079', '', '', '9079')]
['7', '15', '91'] --> 7-15-91 --> 7-15-91

('06/12/94', '06/', '12/', '94') [('06/12/94', '06/', '12/', '94'), ('-10', '-', '', '10')]
['06', '12', '94'] --> 06-12-94 --> 06-12-94

('9/17/84', '9/', '17/', '84') [('9/17/84', '9/', '17/', '84')]
['9', '17', '84'] --> 9-17-84 --> 9-17-84

('2/28/75', '2/', '28/', '75') [('2/28/75', '2/', '28/', '75')]
['2', '28', '75'] --> 2-28-75 --> 2-28-75

('11/22/75', '11/', '22/', '75') [('11/22/75', '11/', '22/', '75')]
['11', '22', '75'] --> 11-22-75 --> 11-22-75

('5/24/91', '5/', '24/', '91') [('5/24/91', '5/', '24/', '91'), ('6/13/92', '6/', '13/', '92'), ('9079', '', '', '9079'), ('7/11/71', '7/', '11/', '71'), ('-10', '-', '', '10'), ('12/26/86', '12/', '26/', '86'), ('9079', '', '', '9079'), ('10/11/1987', '10/', '11/', '1987'), ('9079', '', '', '9079'), ('3/14/95', '3/', '14/', '95'), ('12/01/73', '12/', '01/', '73'), ('9079', '', '', '9079'), ('12/5/2010', '12/', '5/', '2010'), ('08/20/1982', '08/', '20/', '1982'), ('-10', '-', '', '10'), ('7/24/95', '7/', '24/', '95'), ('-10', '-', '', '10'), ('8/06/83', '8/', '06/', '83'), ('9079', '', '', '9079'), ('02/22/92', '02/', '22/', '92'), ('-10', '-', '', '10'), ('6/28/87', '6/', '28/', '87'), ('07/29/1994', '07/', '29/', '1994'), ('9920', '', '', '9920'), ('08/11/78', '08/', '11/', '78'), ('9080', '', '', '9080'), ('10/29/91', '10/', '29/', '91'), ('7/6/91', '7/', '6/', '91'), ('-10', '-', '', '10'), ('1/21/87', '1/', '21/', '87'), ('24', '', '', '24'), ('11/3/1985', '11/', '3/', '1985'), ('7/04/82', '7/', '04/', '82'), ('9080', '', '', '9080'), ('4-13-89', '4-', '13-', '89'), ('25', '', '', '25'), ('7/11/77', '7/', '11/', '77'), ('500', '', '', '500'), ('28', '', '', '28'), ('16', '', '', '16'), ('83', '', '', '83'), ('12', '', '', '12'), ('363', '', '', '363'), ('20', '', '', '20'), ('9/36/308', '9/', '36/', '308'), ('4/12/74', '4/', '12/', '74'), ('09/19/81', '09/', '19/', '81'), ('9079', '', '', '9079'), ('9/6/79', '9/', '6/', '79'), ('12/5/87', '12/', '5/', '87'), ('01/05/1999', '01/', '05/', '1999'), ('4/22/80', '4/', '22/', '80'), ('-10', '-', '', '10'), ('10/04/98', '10/', '04/', '98'), ('-10', '-', '', '10'), ('10-15', '10-', '', '15'), ('6/29/81', '6/', '29/', '81')]
['5', '24', '91'] --> 5-24-91 --> 5-24-91

('8/04/78', '8/', '04/', '78') [('8/04/78', '8/', '04/', '78')]
['8', '04', '78'] --> 8-04-78 --> 8-04-78

('7/07/1974', '7/', '07/', '1974') [('7/07/1974', '7/', '07/', '1974')]
['7', '07', '1974'] --> 7-07-1974 --> 7-07-1974

('09/14/2000', '09/', '14/', '2000') [('09/14/2000', '09/', '14/', '2000'), ('9079', '', '', '9079')]
['09', '14', '2000'] --> 09-14-2000 --> 09-14-2000

('5/18/71', '5/', '18/', '71') [('5/18/71', '5/', '18/', '71')]
['5', '18', '1971'] --> 5-18-1971 --> 5-18-1971

('8/09/1981', '8/', '09/', '1981') [('8/09/1981', '8/', '09/', '1981')]
['8', '09', '1981'] --> 8-09-1981 --> 8-09-1981

('6/05/93', '6/', '05/', '93') [('6/05/93', '6/', '05/', '93'), ('9079', '', '', '9079')]
['6', '05', '93'] --> 6-05-93 --> 6-05-93

('100', '', '', '100') [('100', '', '', '100'), ('290', '', '', '290'), ('260', '', '', '260'), ('8/9/97', '8/', '9/', '97')]
('12/8/82', '12/', '8/', '82') [('12/8/82', '12/', '8/', '82')]
['12', '8', '82'] --> 12-8-82 --> 12-8-82

('8/26/89', '8/', '26/', '89') [('8/26/89', '8/', '26/', '89'), ('9079', '', '', '9079')]
['8', '26', '89'] --> 8-26-89 --> 8-26-89

('10/13/95', '10/', '13/', '95') [('10/13/95', '10/', '13/', '95'), ('9079', '', '', '9079')]
['10', '13', '95'] --> 10-13-95 --> 10-13-95

('4/19/91', '4/', '19/', '91') [('4/19/91', '4/', '19/', '91')]
['4', '19', '91'] --> 4-19-91 --> 4-19-91

('04/08/2004', '04/', '08/', '2004') [('04/08/2004', '04/', '08/', '2004'), ('16', '', '', '16'), ('39', '', '', '39')]
['04', '08', '2004'] --> 04-08-2004 --> 04-08-2004

('9/20/76', '9/', '20/', '76') [('9/20/76', '9/', '20/', '76'), ('9080', '', '', '9080')]
['9', '20', '76'] --> 9-20-76 --> 9-20-76

('12/08/1990', '12/', '08/', '1990') [('12/08/1990', '12/', '08/', '1990'), ('11', '', '', '11')]
['12', '08', '1990'] --> 12-08-1990 --> 12-08-1990

('4/11/1974', '4/', '11/', '1974') [('4/11/1974', '4/', '11/', '1974')]
['4', '11', '1974'] --> 4-11-1974 --> 4-11-1974

('7/18/86', '7/', '18/', '86') [('7/18/86', '7/', '18/', '86'), ('-10', '-', '', '10')]
['7', '18', '86'] --> 7-18-86 --> 7-18-86

('3/31/91', '3/', '31/', '91') [('3/31/91', '3/', '31/', '91')]
['3', '31', '91'] --> 3-31-91 --> 3-31-91

('5/13/72', '5/', '13/', '72') [('5/13/72', '5/', '13/', '72')]
['5', '13', '72'] --> 5-13-72 --> 5-13-72

('011', '', '', '011') [('011', '', '', '011'), ('/14/83', '/', '14/', '83')]
('8/16/92', '8/', '16/', '92') [('8/16/92', '8/', '16/', '92'), ('-10', '-', '', '10')]
['8', '16', '92'] --> 8-16-92 --> 8-16-92

('10/05/97', '10/', '05/', '97') [('10/05/97', '10/', '05/', '97'), ('9079', '', '', '9079')]
['10', '05', '97'] --> 10-05-97 --> 10-05-97

('07/18/2002', '07/', '18/', '2002') [('07/18/2002', '07/', '18/', '2002'), ('9079', '', '', '9079')]
['07', '18', '2002'] --> 07-18-2002 --> 07-18-2002

('9/22/82', '9/', '22/', '82') [('9/22/82', '9/', '22/', '82')]
['9', '22', '82'] --> 9-22-82 --> 9-22-82

('2/24/74', '2/', '24/', '74') [('2/24/74', '2/', '24/', '74'), ('-10', '-', '', '10')]
['2', '24', '74'] --> 2-24-74 --> 2-24-74

('2/03/78', '2/', '03/', '78') [('2/03/78', '2/', '03/', '78'), ('90', '', '', '90')]
['2', '03', '78'] --> 2-03-78 --> 2-03-78

('2/11/2006', '2/', '11/', '2006') [('2/11/2006', '2/', '11/', '2006'), ('9079', '', '', '9079')]
['2', '11', '2006'] --> 2-11-2006 --> 2-11-2006

('21', '', '', '21') [('21', '', '', '21'), ('16', '', '', '16'), ('8/22/83', '8/', '22/', '83')]
('5/04/74', '5/', '04/', '74') [('5/04/74', '5/', '04/', '74')]
['5', '04', '74'] --> 5-04-74 --> 5-04-74

('7/20/2011', '7/', '20/', '2011') [('7/20/2011', '7/', '20/', '2011')]
['7', '20', '2011'] --> 7-20-2011 --> 7-20-2011

('6/17/95', '6/', '17/', '95') [('6/17/95', '6/', '17/', '95')]
['6', '17', '95'] --> 6-17-95 --> 6-17-95

('6/10/72', '6/', '10/', '72') [('6/10/72', '6/', '10/', '72'), ('-10', '-', '', '10')]
['6', '10', '72'] --> 6-10-72 --> 6-10-72

('10/16/82', '10/', '16/', '82') [('10/16/82', '10/', '16/', '82')]
['10', '16', '82'] --> 10-16-82 --> 10-16-82

('12/15/92', '12/', '15/', '92') [('12/15/92', '12/', '15/', '92'), ('9080', '', '', '9080')]
['12', '15', '92'] --> 12-15-92 --> 12-15-92

('12/8/97', '12/', '8/', '97') [('12/8/97', '12/', '8/', '97'), ('-10', '-', '', '10')]
['12', '8', '97'] --> 12-8-97 --> 12-8-97

('4/05/89', '4/', '05/', '89') [('4/05/89', '4/', '05/', '89')]
['4', '05', '89'] --> 4-05-89 --> 4-05-89

('12/04/87', '12/', '04/', '87') [('12/04/87', '12/', '04/', '87'), ('-10', '-', '', '10')]
['12', '04', '87'] --> 12-04-87 --> 12-04-87

('6/20/77', '6/', '20/', '77') [('6/20/77', '6/', '20/', '77')]
['6', '20', '77'] --> 6-20-77 --> 6-20-77

('4/27/2006', '4/', '27/', '2006') [('4/27/2006', '4/', '27/', '2006')]
['4', '27', '2006'] --> 4-27-2006 --> 4-27-2006

('07/17/92', '07/', '17/', '92') [('07/17/92', '07/', '17/', '92'), ('9079', '', '', '9079')]
['07', '17', '92'] --> 07-17-92 --> 07-17-92

('12/22/98', '12/', '22/', '98') [('12/22/98', '12/', '22/', '98'), ('9080', '', '', '9080')]
['12', '22', '98'] --> 12-22-98 --> 12-22-98

('10/02/96', '10/', '02/', '96') [('10/02/96', '10/', '02/', '96')]
['10', '02', '96'] --> 10-02-96 --> 10-02-96

('11/05/90', '11/', '05/', '90') [('11/05/90', '11/', '05/', '90'), ('9079', '', '', '9079')]
['11', '05', '90'] --> 11-05-90 --> 11-05-90

('5/04/77', '5/', '04/', '77') [('5/04/77', '5/', '04/', '77'), ('9079', '', '', '9079')]
['5', '04', '77'] --> 5-04-77 --> 5-04-77

('2/27/96', '2/', '27/', '96') [('2/27/96', '2/', '27/', '96')]
['2', '27', '96'] --> 2-27-96 --> 2-27-96

['2', '27', '96'] --> 24 Jan 2001 --> 24 Jan 2001

['2', '27', '96'] --> 10 Sep 2004 --> 10 Sep 2004

['2', '27', '96'] --> 26 May 1982 --> 26 May 1982

['2', '27', '96'] --> 28 June 2002 --> 28 June 2002

['2', '27', '96'] --> 06 May 1972 --> 06 May 1972

['2', '27', '96'] --> 25 Oct 1987 --> 25 Oct 1987

['2', '27', '96'] --> 14 Oct 1996 --> 14 Oct 1996

['2', '27', '96'] --> 30 Nov 2007 --> 30 Nov 2007

['2', '27', '96'] --> 28 June 1994 --> 28 June 1994

['2', '27', '96'] --> 14 Jan 1981 --> 14 Jan 1981

['2', '27', '96'] --> 10 Oct 1985 --> 10 Oct 1985

['2', '27', '96'] --> 11 February 1985 --> 11 February 1985

['2', '27', '96'] --> 10 Feb 1983 --> 10 Feb 1983

['2', '27', '96'] --> 05 Feb 1992 --> 05 Feb 1992

['2', '27', '96'] --> 21 Oct 2012 --> 21 Oct 2012

['2', '27', '96'] --> 14 Feb 1995 --> 14 Feb 1995

['2', '27', '96'] --> 30 May 2016 --> 30 May 2016

['2', '27', '96'] --> 22 Jan 1996 --> 22 Jan 1996

['2', '27', '96'] --> 14 Oct 1992 --> 14 Oct 1992

['2', '27', '96'] --> 06 Oct 2003 --> 06 Oct 2003

['2', '27', '96'] --> 18 Oct 1999 --> 18 Oct 1999

['2', '27', '96'] --> 11 Nov 2004 --> 11 Nov 2004

['2', '27', '96'] --> 30 May 2001 --> 30 May 2001

['2', '27', '96'] --> 02 Feb 1978 --> 02 Feb 1978

['2', '27', '96'] --> 09 Sep 1989 --> 09 Sep 1989

['2', '27', '96'] --> 12 March 1980 --> 12 March 1980

['2', '27', '96'] --> 22 June 1990 --> 22 June 1990

['2', '27', '96'] --> 28 Sep 2015 --> 28 Sep 2015

['2', '27', '96'] --> 13 Jan 1972 --> 13 Jan 1972

['2', '27', '96'] --> 06 Mar 1974 --> 06 Mar 1974

['2', '27', '96'] --> 10 Oct 1974 --> 10 Oct 1974

['2', '27', '96'] --> 26 May 1974 --> 26 May 1974

['2', '27', '96'] --> 10 Feb 1990 --> 10 Feb 1990

['2', '27', '96'] --> 23 Aug 2000 --> 23 Aug 2000

['2', '27', '96'] --> 26 May 2001 --> 26 May 2001

['2', '27', '96'] --> 21 Oct 2007 --> 21 Oct 2007

['2', '27', '96'] --> 19 Oct 2016 --> 19 Oct 2016

['2', '27', '96'] --> 05 Mar 1974 --> 05 Mar 1974

['2', '27', '96'] --> 29 Jan 1994 --> 29 Jan 1994

['2', '27', '96'] --> 21 Oct 1978 --> 21 Oct 1978

['2', '27', '96'] --> 18 August 1975 --> 18 August 1975

['2', '27', '96'] --> 11 Nov 1996 --> 11 Nov 1996

['2', '27', '96'] --> 01 Oct 1979 --> 01 Oct 1979

['2', '27', '96'] --> 13 Oct 1986 --> 13 Oct 1986

['2', '27', '96'] --> 21 Oct 1995 --> 21 Oct 1995

['2', '27', '96'] --> 24 Jan 2011 --> 24 Jan 2011

['2', '27', '96'] --> 04 Oct 1972 --> 04 Oct 1972

['2', '27', '96'] --> 23 Aug 1993 --> 23 Aug 1993

['2', '27', '96'] --> 18 Oct 2006 --> 18 Oct 2006

['2', '27', '96'] --> 04 Dec 1988 --> 04 Dec 1988

['2', '27', '96'] --> 21 Oct 1983 --> 21 Oct 1983

['2', '27', '96'] --> 26 May 2010 --> 26 May 2010

['2', '27', '96'] --> 18 Jan 1990 --> 18 Jan 1990

['2', '27', '96'] --> 15 Jun 1985 --> 15 Jun 1985

['2', '27', '96'] --> 10 Dec 1982 --> 10 Dec 1982

['2', '27', '96'] --> 09 Dec 1988 --> 09 Dec 1988

['2', '27', '96'] --> 18 August 1995 --> 18 August 1995

['2', '27', '96'] --> 13 June 1974 --> 13 June 1974

['2', '27', '96'] --> 26 May 2008 --> 26 May 2008

['2', '27', '96'] --> 11 Nov 2002 --> 11 Nov 2002

['2', '27', '96'] --> 17 Aug 1985 --> 17 Aug 1985

['2', '27', '96'] --> 13 Oct 2016 --> 13 Oct 2016

['2', '27', '96'] --> 14 Jan 2008 --> 14 Jan 2008

['2', '27', '96'] --> 12 March 2004 --> 12 March 2004

['2', '27', '96'] --> 21 Oct 1977 --> 21 Oct 1977

['2', '27', '96'] --> 10 Aug 2000 --> 10 Aug 2000

['2', '27', '96'] --> 30 Nov 1972 --> 30 Nov 1972

['2', '27', '96'] --> 06 May 1993 --> 06 May 1993

['2', '27', '96'] --> 18 Jan 1995 --> 18 Jan 1995

['2', '27', '96'] --> April 11, 1990 --> April 11 1990

['2', '27', '96'] --> May 30, 2001 --> May 30 2001

['2', '27', '96'] --> Feb 18, 1994 --> Feb 18 1994

['2', '27', '96'] --> February 18, 1981 --> February 18 1981

['2', '27', '96'] --> October. 11, 2013 --> October 11 2013

['2', '27', '96'] --> Jan 24 1986 --> Jan 24 1986

['2', '27', '96'] --> July 26, 1978 --> July 26 1978

['2', '27', '96'] --> December 23, 1999 --> December 23 1999

['2', '27', '96'] --> May 15, 1989 --> May 15 1989

['2', '27', '96'] --> September 06, 1995 --> September 06 1995

['2', '27', '96'] --> Mar. 10, 1976 --> Mar 10 1976

['2', '27', '96'] --> Jan 27, 1983 --> Jan 27 1983

['2', '27', '96'] --> October 23 1990 --> October 23 1990

['2', '27', '96'] --> August 12 2004 --> August 12 2004

['2', '27', '96'] --> September 01, 2012 --> September 01 2012

['2', '27', '96'] --> July 25, 1983 --> July 25 1983

['2', '27', '96'] --> August 11, 1989 --> August 11 1989

['2', '27', '96'] --> April 17, 1992 --> April 17 1992

['2', '27', '96'] --> July 24, 1999 --> July 24 1999

['2', '27', '96'] --> July 11, 1997 --> July 11 1997

['2', '27', '96'] --> Sep. 10, 1974 --> Sep 10 1974

['2', '27', '96'] --> August 14, 1981 --> August 14 1981

['2', '27', '96'] --> Nov 11, 1988 --> Nov 11 1988

['2', '27', '96'] --> June 13, 2011 --> June 13 2011

['2', '27', '96'] --> May 14, 1989 --> May 14 1989

['2', '27', '96'] --> Dec 14 1975 --> Dec 14 1975

['2', '27', '96'] --> June 25, 2012 --> June 25 2012

['2', '27', '96'] --> Oct 18, 1980 --> Oct 18 1980

['2', '27', '96'] --> May 15, 1998 --> May 15 1998

['2', '27', '96'] --> October 14 1974 --> October 14 1974

['2', '27', '96'] --> July 25, 1998 --> July 25 1998

['2', '27', '96'] --> June 15, 1972 --> June 15 1972

['2', '27', '96'] --> January 07, 1991 --> January 07 1991

['2', '27', '96'] --> September. 15, 2011 --> September 15 2011

['2', '27', '96'] --> 1 September 1985 --> 1 September 1985

['2', '27', '96'] --> 1 June 2011 --> 1 June 2011

['2', '27', '96'] --> 1 May 1986 --> 1 May 1986

['2', '27', '96'] --> 1 May 2016 --> 1 May 2016

['2', '27', '96'] --> 1 July 1977 --> 1 July 1977

['2', '27', '96'] --> 1 July, 1990 --> 1 July 1990

['2', '27', '96'] --> 1 Jul 2003 --> 1 Jul 2003

['2', '27', '96'] --> 1 Oct 2015 --> 1 Oct 2015

['2', '27', '96'] --> 1 May 1995 --> 1 May 1995

['2', '27', '96'] --> 1 February 1976 --> 1 February 1976

['2', '27', '96'] --> 1 January 1995 --> 1 January 1995

['2', '27', '96'] --> 1 Feb 1978 --> 1 Feb 1978

['2', '27', '96'] --> 1 May, 2011 --> 1 May 2011

['2', '27', '96'] --> 1 May 2004 --> 1 May 2004

['2', '27', '96'] --> 1 Nov 2010 --> 1 Nov 2010

['2', '27', '96'] --> 1 Sep 2012 --> 1 Sep 2012

['2', '27', '96'] --> 1 January, 2013 --> 1 January 2013

['2', '27', '96'] --> 1 November 1990 --> 1 November 1990

['2', '27', '96'] --> 1 July 1981 --> 1 July 1981

['2', '27', '96'] --> 1 May 1983 --> 1 May 1983

['2', '27', '96'] --> 1 July 1995 --> 1 July 1995

['2', '27', '96'] --> 1 April 1993 --> 1 April 1993

['2', '27', '96'] --> 1 May 2005 --> 1 May 2005


8      1971-04-10
53     1971-05-18
1      1971-07-08
26     1971-09-12
419    1972-01-01
          ...
221    2016-02-01
199    2016-05-01
109    2016-05-30
154    2016-10-13
129    2016-10-19
Length: 444, dtype: object

In [183]:
a = '-8-2000'
a.startswith('-')

True